### PR TITLE
Cope with `field_transformer` being a generator

### LINKED ISSUE #1416: Creating a Subclassed instance now errors with `got an unexpected keyword argument`
We just noticed this in Airflow CI on upgrading to 25.2.0.

The error is

```
ERROR    airflow.models.dagbag.DagBag:dagbag.py:394 Failed to import: /opt/airflow/airflow/example_dags/example_dynamic_task_mapping.py
Traceback (most recent call last):
  File "/opt/airflow/airflow/models/dagbag.py", line 384, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow/example_dags/example_dynamic_task_mapping.py", line 27, in <module>
    with DAG(dag_id="example_dynamic_task_mapping", schedule=None, start_date=datetime(2022, 3, 4)) as dag:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'dag_id'
```

(Yes, I know your view on subclassing. I don't disagree either)

Minimal repro case:

```python
import attrs

def _all_after_dag_id_to_kw_only(cls, fields: list[attrs.Attribute]):
    i = iter(fields)
    f = next(i)
    if f.name != "dag_id":
        raise RuntimeError("dag_id was not the first field")
    yield f

    for f in i:
        yield f.evolve(kw_only=True)


@attrs.define(field_transformer=_all_after_dag_id_to_kw_only)
class Base:
    dag_id: str
    has_default: str = "default"


@attrs.define()
class Subclass(Base):
    other: bool


x = Subclass(dag_id="foo", other=False)

print(repr(x))
print(attrs.__version__)
```

### PR DESCRIPTION
**Pull request by ashb**
This worked on 25.1.0 but was inadvertently broken by #1401

Fixes #1416

# Pull Request Check List

- [x] Do **not** open pull requests from your `main` branch – **use a separate branch**!
  - There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a branch from your main branch, push it, and open the pull request from the new branch.
  - This is not a pre-requisite for your pull request to be accepted, but **you have been warned**.
- [x] Added **tests** for changed code.
  Our CI fails if coverage is not 100%.
- [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [ ] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [ ] ...and used in the stub test file `tests/typing_example.py`.
    - [ ] If they've been added to `attr/__init__.pyi`, they've *also* been re-imported in `attrs/__init__.pyi`.
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changes to the signatures of `@attr.s()` and `@attrs.define()` have to be added by hand too.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
          The next version is the second number in the current release + 1.
          The first number represents the current year.
          So if the current version on PyPI is 22.2.0, the next version is gonna be 22.3.0.
          If the next version is the first in the new year, it'll be 23.1.0.
      - [ ] If something changed that affects both `attrs.define()` and `attr.s()`, you have to add version directives to both.
- [ ] Documentation in `.rst` and `.md` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).
- [x] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

### CODE REVIEW

**Comment by ashb** [comment]
I think this should have coverage, but pre-commit was complaining about that locally, but I couldn't quite work out what it was saying wasn't covered.

File: src/attr/_make.py [hunk 1]
```diff
@@ -450,6 +450,9 @@ def _transform_attrs(
     if field_transformer is not None:
         attrs = field_transformer(cls, attrs)
 
+        if inspect.isgenerator(attrs):
```
Comment (uranusjr) [inline src/attr/_make.py:453]: Instead of generator specifically, would it be better to make this cover all iterators instead? A simple check would be `if hasattr(attrs, "__next__")`

Comment (ashb) [reply src/attr/_make.py:453]: Perhaps,  I always feel icky looking at dunders like that though.

WDYT @hynek ?

Comment (hynek) [reply src/attr/_make.py:453]: Does anything speak against calling tuple unconditionally? The inspect isn't free either.

Comment (ashb) [reply src/attr/_make.py:453]: That if you returned something else odd (like a single value? I dunno) you 'd end up with that wrapped in a tuple.

Either way it's going to behave oddly or give you an error. 

Happy to just make it a tuple unconditionally. Perhaps worht an `if not isinstance(attrs, (list,tuple))` check too?

File: src/attr/_make.py [hunk 2]
```diff
@@ -450,6 +450,9 @@ def _transform_attrs(
...
+            attrs = tuple(attrs)
```
Comment (ashb) [inline src/attr/_make.py:454]:
```suggestion
        if not isinstance(attrs, (list, tuple)):
            attrs = tuple(attrs)
```

Comment (ashb) [reply src/attr/_make.py:454]: It does pass without the isinstance check, but it seems more wasteful to turn a list into a tuple when? Dunno

File: src/attr/_make.py [hunk 3]
```diff
@@ -450,6 +450,9 @@ def _transform_attrs(
...
+
```
Comment (ashb) [inline src/attr/_make.py:455]:
```suggestion
        attrs = tuple(field_transformer(cls, attrs))

```

File: src/attr/_make.py (hunk 2 above)
Comment (ashb) [inline src/attr/_make.py:454]:
```suggestion
        attrs = tuple(field_transformer(cls, attrs))
```

Comment (ashb) [reply src/attr/_make.py:454]: I've tested both the suggestions locally, they both work for everything covered in the tests, so pick which ever you like best I think @hynek

**Review by hynek — APPROVED** [review]
thanks!
