### ISSUE TITLE
Correct way to validate if something is an int or float?

### ISSUE THREAD

**Issue by VideoPlayerCode** [python-attrs/attrs#584]
My attempt:

```python
from typing import Union
import numbers

import attr

@attr.s(auto_attribs=True)
class Trigger:
    value: Union[float, int] = attr.ib(kw_only=True, validator=attr.validators.instance_of(numbers.Real))
```

This works but mypy complains. What to do? For now I scrapped it and just went with `value: int`. But for future reference, how do we check if a value is either int or float?

**Comment by hynek** [comment]
To me, mypy complains about the mismatch of you type annotation and your instance_of validators:

```
error: Incompatible types in assignment (expression has type "Real", variable has type "Union[float, int]")
```

Changing it to `    value: Union[float, int] = attr.ib(kw_only=True, validator=attr.validators.instance_of((float,int)))` makes it pass.

---

Also please use StackOverflow for questions in the future to make the fixes googleable (and doesn't require only the maintainers to respond) – thank you!

**Comment by VideoPlayerCode** [comment]
@hynek Thanks a lot for your answer and sorry for taking up your time! At least this ticket is indexed by Google if someone searches for this problem.

For reference:
http://www.attrs.org/en/stable/api.html#attr.validators.instance_of

I hadn't seen the `isinstance()` subtlety of that function that the first time I read it and thought it only took 1 type. That's why I tried `numbers.Real` since both `int` and `float` are "reals". But I see now that the validator also takes a tuple of possible valid types. That's great!

**Comment by marwan116** [comment]
> To me, mypy complains about the mismatch of you type annotation and your instance_of validators:
> 
> ```
> error: Incompatible types in assignment (expression has type "Real", variable has type "Union[float, int]")
> ```
> 
> Changing it to ` value: Union[float, int] = attr.ib(kw_only=True, validator=attr.validators.instance_of((float,int)))` makes it pass.
> 
> Also please use StackOverflow for questions in the future to make the fixes googleable (and doesn't require only the maintainers to respond) – thank you!

Just came across this - mypy complains about this in my case (perhaps because I am using a newer version of mypy ?)
```
error: Argument 1 to "instance_of" has incompatible type "Tuple[Type[float], Type[int]]";
expected "Union[Tuple[Type[int], ...], Type[int]]"  [arg-type]
            validator=attr.validators.instance_of((float, int)), default=1
```

**Comment by euresti** [comment]
What version of `mypy` are you using?  And which version of `attrs`

**Comment by marwan116** [comment]
@euresti -

attrs v19.3.0 
mypy v0.770

and my reproducible example is 
```
from typing import Union
import attr

@attr.s(kw_only=True, auto_attribs=True)
class A:
    p: Union[float, int] = attr.ib(
        validator=attr.validators.instance_of((float, int)), default=1
    )
```

```
expected "Union[Tuple[Type[int], ...], Type[int]]"  [arg-type]
            validator=attr.validators.instance_of((float, int)), default=1
```

**Comment by euresti** [comment]
Interesting.  Must've been a mypy bug that got fixed. The code you posted works fine with with mypy 0.782 and attrs 19.3.0

**Comment by marwan116** [comment]
I see - thanks for checking :)
