### ISSUE TITLE
TypeError resolving union types with __future__ annotations

### ISSUE THREAD

**Issue by alexchandel** [python-attrs/attrs#831]
The following valid Python 3.9 code fails:
```python
from __future__ import annotations
import attr

@attr.s(auto_attribs=True, slots=True)
class Line():
    line: str | None

attr.resolve_types(Line)
```

attrs throws an error evaluating the type union:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/attr/_funcs.py", line 383, in resolve_types
    cls.__attrs_types_resolved__
AttributeError: type object 'Line' has no attribute '__attrs_types_resolved__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/GitHub/housealert/bug.py", line 12, in <module>
    attr.resolve_types(Line)
  File "/usr/local/lib/python3.9/site-packages/attr/_funcs.py", line 387, in resolve_types
    hints = typing.get_type_hints(cls, globalns=globalns, localns=localns)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1417, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

attrs needs to import `annotations` from `__future__`, or somehow allow them in its eval.

**Comment by euresti** [comment]
I think `str | None`  only works in python 3.10  https://www.python.org/dev/peps/pep-0604/
So I'm not sure how this would ever work.  All `resolve_types` does is `eval` the string that is contained in the annotation. i.e. `eval("str | None")`  which isn't valid python in 3.9

**Comment by alexchandel** [comment]
It works in Python 3.9 with `from __future__ import annotations`.  `str | None` is defined as valid in Python 3.9 (and 3.8 and 3.7) if `annotations` was imported from `__future__` in that module.

**Comment by euresti** [comment]
`from __future__ import annotations` just means "anytime you see an annotation turn it into a string."  So at run time your code literally looks like:

```
@attr.s(auto_attribs=True, slots=True)
class Line():
    line: "str | None"
```

This means you can put all sorts of stuff into the annotation and python would run it just fine.
e.g.
```
from __future__ import annotations
import attr

@attr.s(auto_attribs=True, slots=True)
class Line():
    line: omg+such-fun[what222]*123

x = Line("hi")
print(x)
```

If you run the above it'll just print out `Line(line='hi')`

**Comment by alexchandel** [comment]
Very strange.  I'm unsure why it works for me with `annotations`.  I have 3.9…
